### ISSUE TITLE
TypeError: Cannot read property 'getQueryType' of undefined

### ISSUE THREAD

**Issue by jascodes** [graphql-editor/graphql-zeus#127]
I am getting `TypeError: Cannot read property 'getQueryType' of undefined` when trying to generate client for hasura generated graphql schema.

Details are below, maybe this is related to #125

Cmd run = `zeus https://jc-hc.herokuapp.com/v1/graphql .`
Hasura Graphql Explorer = `https://jc-hc.herokuapp.com/console/api-explorer`
Error log
```
schema {
  query: query_root
  mutation: mutation_root
  subscription: subscription_root
}

"""mutation root"""
type mutation_root {
  """
  delete data from the table: "test"
  """
  delete_test(
    """filter the rows which have to be deleted"""
    where: test_bool_exp!
  ): test_mutation_response

  """
  insert data into the table: "test"
  """
  insert_test(
    """the rows to be inserted"""
    objects: [test_insert_input!]!

    """on conflict condition"""
    on_conflict: test_on_conflict
  ): test_mutation_response

  """
  update data of the table: "test"
  """
  update_test(
    """sets the columns of the filtered rows to the given values"""
    _set: test_set_input

    """filter the rows which have to be updated"""
    where: test_bool_exp!
  ): test_mutation_response
}

"""column ordering options"""
enum order_by {
  """in the ascending order, nulls last"""
  asc

  """in the ascending order, nulls first"""
  asc_nulls_first

  """in the ascending order, nulls last"""
  asc_nulls_last

  """in the descending order, nulls first"""
  desc

  """in the descending order, nulls first"""
  desc_nulls_first

  """in the descending order, nulls last"""
  desc_nulls_last
}

"""query root"""
type query_root {
  """
  fetch data from the table: "test"
  """
  test(
    """distinct select on columns"""
    distinct_on: [test_select_column!]

    """limit the number of rows returned"""
    limit: Int

    """skip the first n rows. Use only with order_by"""
    offset: Int

    """sort the rows by one or more columns"""
    order_by: [test_order_by!]

    """filter the rows returned"""
    where: test_bool_exp
  ): [test!]!

  """
  fetch aggregated fields from the table: "test"
  """
  test_aggregate(
    """distinct select on columns"""
    distinct_on: [test_select_column!]

    """limit the number of rows returned"""
    limit: Int

    """skip the first n rows. Use only with order_by"""
    offset: Int

    """sort the rows by one or more columns"""
    order_by: [test_order_by!]

    """filter the rows returned"""
    where: test_bool_exp
  ): test_aggregate!

  """fetch data from the table: "test" using primary key columns"""
  test_by_pk(t: String!): test
}

"""
expression to compare columns of type String. All fields are combined with logical 'AND'.
"""
input String_comparison_exp {
  _eq: String
  _gt: String
  _gte: String
  _ilike: String
  _in: [String!]
  _is_null: Boolean
  _like: String
  _lt: String
  _lte: String
  _neq: String
  _nilike: String
  _nin: [String!]
  _nlike: String
  _nsimilar: String
  _similar: String
}

"""subscription root"""
type subscription_root {
  """
  fetch data from the table: "test"
  """
  test(
    """distinct select on columns"""
    distinct_on: [test_select_column!]

    """limit the number of rows returned"""
    limit: Int

    """skip the first n rows. Use only with order_by"""
    offset: Int

    """sort the rows by one or more columns"""
    order_by: [test_order_by!]

    """filter the rows returned"""
    where: test_bool_exp
  ): [test!]!

  """
  fetch aggregated fields from the table: "test"
  """
  test_aggregate(
    """distinct select on columns"""
    distinct_on: [test_select_column!]

    """limit the number of rows returned"""
    limit: Int

    """skip the first n rows. Use only with order_by"""
    offset: Int

    """sort the rows by one or more columns"""
    order_by: [test_order_by!]

    """filter the rows returned"""
    where: test_bool_exp
  ): test_aggregate!

  """fetch data from the table: "test" using primary key columns"""
  test_by_pk(t: String!): test
}

"""
columns and relationships of "test"
"""
type test {
  t: String!
}

"""
aggregated selection of "test"
"""
type test_aggregate {
  aggregate: test_aggregate_fields
  nodes: [test!]!
}

"""
aggregate fields of "test"
"""
type test_aggregate_fields {
  count(columns: [test_select_column!], distinct: Boolean): Int
  max: test_max_fields
  min: test_min_fields
}

"""
order by aggregate values of table "test"
"""
input test_aggregate_order_by {
  count: order_by
  max: test_max_order_by
  min: test_min_order_by
}

"""
input type for inserting array relation for remote table "test"
"""
input test_arr_rel_insert_input {
  data: [test_insert_input!]!
  on_conflict: test_on_conflict
}

"""
Boolean expression to filter rows from the table "test". All fields are combined with a logical 'AND'.
"""
input test_bool_exp {
  _and: [test_bool_exp]
  _not: test_bool_exp
  _or: [test_bool_exp]
  t: String_comparison_exp
}

"""
unique or primary key constraints on table "test"
"""
enum test_constraint {
  """unique or primary key constraint"""
  test_pkey
}

"""
input type for inserting data into table "test"
"""
input test_insert_input {
  t: String
}

"""aggregate max on columns"""
type test_max_fields {
  t: String
}

"""
order by max() on columns of table "test"
"""
input test_max_order_by {
  t: order_by
}

"""aggregate min on columns"""
type test_min_fields {
  t: String
}

"""
order by min() on columns of table "test"
"""
input test_min_order_by {
  t: order_by
}

"""
response of any mutation on the table "test"
"""
type test_mutation_response {
  """number of affected rows by the mutation"""
  affected_rows: Int!

  """data of the affected rows by the mutation"""
  returning: [test!]!
}

"""
input type for inserting object relation for remote table "test"
"""
input test_obj_rel_insert_input {
  data: test_insert_input!
  on_conflict: test_on_conflict
}

"""
on conflict condition type for table "test"
"""
input test_on_conflict {
  constraint: test_constraint!
  update_columns: [test_update_column!]!
  where: test_bool_exp
}

"""
ordering options when selecting data from "test"
"""
input test_order_by {
  t: order_by
}

"""
select columns of table "test"
"""
enum test_select_column {
  """column name"""
  t
}

"""
input type for updating data in table "test"
"""
input test_set_input {
  t: String
}

"""
update columns of table "test"
"""
enum test_update_column {
  """column name"""
  t
}

schema{
        query: query_root,
        mutation: mutation_root,
        subscription: subscription_root
}
(node:20606) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getQueryType' of undefined
    at Function.Parser.parse (/home/jas/.config/yarn/global/node_modules/graphql-zeus/lib/Parser/index.js:57:26)
    at Function.Parser.parseAddExtensions (/home/jas/.config/yarn/global/node_modules/graphql-zeus/lib/Parser/index.js:94:27)
    at Function.TranslateGraphQL.javascript (/home/jas/.config/yarn/global/node_modules/graphql-zeus/lib/TranslateGraphQL/index.js:16:34)
    at /home/jas/.config/yarn/global/node_modules/graphql-zeus/lib/CLI/CLIClass.js:47:66
    at Generator.next (<anonymous>)
    at fulfilled (/home/jas/.config/yarn/global/node_modules/graphql-zeus/lib/CLI/CLIClass.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:20606) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20606) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by aexol** [comment]
Fixed in 2.5.0
