### ISSUE TITLE
Hasura remote schemas with error on types 

### ISSUE THREAD

**Issue by gilvaju** [graphql-editor/graphql-zeus#221]
When trying to generate the new hasura types after inserting a relationship with a remote schema, I am getting the following error:

```
GraphQLError [Object]: Syntax Error: Cannot parse the unexpected character ".".
    at syntaxError (/home/alex/Code/Comigo/goerp-client-web/node_modules/graphql/error/syntaxError.js:15:10)
    at readToken (/home/alex/Code/Comigo/goerp-client-web/node_modules/graphql/language/lexer.js:360:40)
    at Lexer.lookahead (/home/alex/Code/Comigo/goerp-client-web/node_modules/graphql/language/lexer.js:75:108)
    at Lexer.advance (/home/alex/Code/Comigo/goerp-client-web/node_modules/graphql/language/lexer.js:58:35)
    at Parser.expectToken (/home/alex/Code/Comigo/goerp-client-web/node_modules/graphql/language/parser.js:1408:19)
    at Parser.parseName (/home/alex/Code/Comigo/goerp-client-web/node_modules/graphql/language/parser.js:98:22)
    at Parser.parseNamedType (/home/alex/Code/Comigo/goerp-client-web/node_modules/graphql/language/parser.js:674:18)
    at Parser.parseTypeReference (/home/alex/Code/Comigo/goerp-client-web/node_modules/graphql/language/parser.js:652:19)
    at Parser.parseInputValueDef (/home/alex/Code/Comigo/goerp-client-web/node_modules/graphql/language/parser.js:913:21)
    at Parser.optionalMany (/home/alex/Code/Comigo/goerp-client-web/node_modules/graphql/language/parser.js:1503:28) {
  locations: [ { line: 518, column: 64 } ]
}
(node:44010) UnhandledPromiseRejectionWarning: Error: Cannot parse the schema
    at Function.Parser.parse (/home/alex/Code/Comigo/goerp-client-web/node_modules/graphql-js-tree/lib/Parser/index.js:68:15)
    at /home/alex/Code/Comigo/goerp-client-web/node_modules/graphql-zeus/lib/CLI/CLIClass.js:36:43
    at Generator.next (<anonymous>)
    at fulfilled (/home/alex/Code/Comigo/goerp-client-web/node_modules/graphql-zeus/lib/CLI/CLIClass.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:44010) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:44010) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm using hasura version 2.0.9 and zeus version 3.1.5

**Comment by aexol** [comment]
Hi, can you provide schema or schema URL?

**Comment by gilvaju** [comment]
Hi @aexol, thanks for the asnwer, follows the schema: 

https://gist.github.com/gilvaju/2e3974a14228ea22b96bc2f0d9f70496#file-gistfile1-txt

**Comment by aexol** [comment]
Dot inside schema is invalid

**Comment by gilvaju** [comment]
> Dot inside schema is invalid

![2021-11-06-085859_1280x1024_scrot](https://user-images.githubusercontent.com/677039/140614135-98e693cf-5b17-4a60-be62-44fcbf53de61.png)

In this case, for remote relationships, hasura uses the point as we can see in the image. Is there any way I can get around this?

**Comment by aexol** [comment]
Will check on monday, we already support some spec invalid stuff in zeus.

**Comment by gilvaju** [comment]
Hi, I'm sorry for the charge, but were you able to analyze any solution? I figured that in version 2.1 of hasura it could be solved, being able to edit the name, but it is not possible yet

**Comment by Alex-Ferreira-Santos** [comment]
same problem here...

**Comment by henriqwe** [comment]
i have the same problem

**Comment by gilvaju** [comment]
> Will check on monday, we already support some spec invalid stuff in zeus.

Hi @aexol could you see any solution to our problem? Is there anything we can do to get around this problem on our side?

**Comment by BenoitRanque** [comment]
Note: this is a bug in hasura, I have created an issue with more details at https://github.com/hasura/graphql-engine/issues/8002
