### ISSUE TITLE
build is failing locally

### ISSUE THREAD

**Issue by Gozala** [graphql-editor/graphql-zeus#223]
I was trying to write a patch for the issue #222 but runing into the problem with getting up and running, after cloning a repo and running following locally I encounter the problem:

```js
git clone git@github.com:graphql-editor/graphql-zeus.git
cd graphql-zeus
yarn install
yarn build
yarn run v1.22.10
$ ttsc --build tsconfig.build.json
/Users/gozala/Projects/graphql-zeus/node_modules/typescript/lib/typescript.js:112634
                throw e;
                ^

TypeError: typescript_1.default.updateNode is not a function
    at /Users/gozala/Projects/graphql-zeus/node_modules/typescript-transform-paths/lib/index.js:126:63
    at update (/Users/gozala/Projects/graphql-zeus/node_modules/typescript-transform-paths/lib/index.js:106:20)
    at visit (/Users/gozala/Projects/graphql-zeus/node_modules/typescript-transform-paths/lib/index.js:123:24)
    at visitNodes (/Users/gozala/Projects/graphql-zeus/node_modules/typescript/lib/typescript.js:85211:48)
    at visitLexicalEnvironment (/Users/gozala/Projects/graphql-zeus/node_modules/typescript/lib/typescript.js:85251:22)
    at Object.visitEachChild (/Users/gozala/Projects/graphql-zeus/node_modules/typescript/lib/typescript.js:85793:55)
    at /Users/gozala/Projects/graphql-zeus/node_modules/typescript-transform-paths/lib/index.js:56:37
    at transformSourceFileOrBundle (/Users/gozala/Projects/graphql-zeus/node_modules/typescript/lib/typescript.js:86489:57)
    at transformation (/Users/gozala/Projects/graphql-zeus/node_modules/typescript/lib/typescript.js:105088:24)
    at transformRoot (/Users/gozala/Projects/graphql-zeus/node_modules/typescript/lib/typescript.js:105115:82)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Gozala** [comment]
I suspect some dependencies got minor version bumps which broke things
